# Generated by Django 2.1.1 on 2018-09-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180903_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_latest_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
