# Generated by Django 2.1.1 on 2018-09-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180904_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='misc_products',
            options={'ordering': ('name',), 'verbose_name': 'misc product', 'verbose_name_plural': 'miscproducts'},
        ),
    ]
