# Generated by Django 2.1.1 on 2018-09-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180904_0326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='misc_products',
            options={'ordering': ('name',), 'verbose_name': 'misc product', 'verbose_name_plural': 'misc products'},
        ),
        migrations.AlterField(
            model_name='apparel_products',
            name='season',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Season'),
        ),
    ]
