# Generated by Django 2.1.1 on 2018-09-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='season'),
        ),
    ]
